### ISSUE TITLE
Publish to html preview

### ISSUE THREAD

**Issue by mrkwjc** [lionel-rigoux/pandemic-plugin#3]
Hi!
Thank you for pandemic. :) It simplifies my work greatly.

However, i'd like to ask if there are some plans to extend the publishing options to html format, mostly to get a lightweight preview of things in atom. Such preview might have syncing with the source just like the markdown-preview has. Unfortunately i'm not skilled enough to code such features myself, so i'm voting here for this.

BTW. Currently i'm using pdf-view package to preview the resulting pdf, but... this is heavy and no syncing is available.

Regards,
Marek

**Comment by lionel-rigoux** [comment]
Hi Marek,
Thanks for your feedback! I'm glad to hear that it simplifies the life of someone else out there...

If you only want to have a quick live preview without styling, you could use [markdown-preview-plus](https://atom.io/packages/markdown-preview-plus). With the correct configuration of the plugin (eg. pandoc filters) you'll get a live preview similar to the pdf output minus the styling.

Otherwise, you could already use pandemic to generate an html file! You just need to specify an html recipe (that you would need to create yourself), or to do the following hack:

- create a template.css file next to the file you want to compile containing all the styling info (you can a ready made on the web, like [this one](https://gist.githubusercontent.com/killercup/5917178/raw/40840de5352083adb2693dc742e9f75dbb18650f/pandoc.css)
-  add the following to the YAML header of your markdown document:
```
---
title: 'the title'
pandemic:
  format: html
---
```

Then compiling will generate an html version of the document you can open with your favorite explorer. You'll also have to find a way to automatically reload the page when the html file change.
Of course this is only worth it if you want something different from what the markdown-preview plus offers (I personnaly only use this one when I write, and only use pandoc for the pdf generation).

I realise now that the default html template does not work well in pandemic, you shouldn't have to specify the title nor create the css file, indicating the hrml format should be enough to trigger a default behaviour. I'll look into that!

**Comment by lionel-rigoux** [comment]
Any luck? Can I close the issue?

**Comment by mrkwjc** [comment]
Yes. Thank you, I'm writing now previewing in markdown-preview-plus and then exporting to pdf with pandemic plugin, just as you suggested. However there are some troubles with live preview because live syncing is broken when using pandoc-eqnos filter (see https://github.com/atom-community/markdown-preview-plus/issues/446), but this is still very nice solution for me...

**Comment by lionel-rigoux** [comment]
I am sure that the preview community will eventually come with a good solution. I am glad you found a workaround to continue using pandemic!
